# Generated by Django 4.2.16 on 2024-11-01 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0007_productpricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDropAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='目标价格')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='通知邮箱')),
                ('active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_drop_alerts', to='products.product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_drop_alerts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
