# Generated by Django 4.2.16 on 2024-10-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='商品ID')),
                ('platform', models.CharField(max_length=50, verbose_name='平台名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('link', models.URLField(verbose_name='商品链接')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='图片链接')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='店铺名称')),
                ('store_link', models.URLField(blank=True, null=True, verbose_name='店铺链接')),
            ],
        ),
    ]
