# Generated by Django 4.2.16 on 2024-10-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(unique=True, verbose_name='商品ID'),
        ),
    ]
