# Generated by Django 4.2.16 on 2024-10-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='商品ID'),
        ),
    ]
